spring:
  application:
    name: payment-service
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

  datasource:
    url: jdbc:postgresql://localhost:5432/omsdb-pay
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >-
          payment:com.store.paymenet.dto.paymentTemplateDTO


sendgrid:
  api-key: "local"

notification:
  topics:
    payment-notification: payment-notification

server:
  port: 4442

razorpay:
  key_id: rzp_test_TSl6x2iqTQMFG1
  secret: KG0XVzVudsNGLR3dSN9pWZZX


