spring:
  application:
    name: payment

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update

  management:
    endpoints:
      web:
        exposure:
          include: "*"

    endpoint:
      health:
        show-details: always


